### ISSUE TITLE
update

### ISSUE THREAD

**Issue by readyztw** [kyfuse/AlphaLoL#2]
I'm so sorry, sir. can you please update the release version of ur ai (the 0.2.3 one)? the idea is superior, I just want to test it on top lane with bots. no leeching or lvlbot purposes. it's just so exciting to follow the logic of this ai.

**Comment by Giantpizzahead** [comment]
Hey, sorry for not responding, I stopped working on the bot a while back and saw this while cleaning up repos. Seeing as Riot recently released Vanguard for League, I think none of the versions would work anymore (and would definitely be flagged), so I'll close this issue. :/
